# Generated by Django 4.2.6 on 2023-10-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bollapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservemodel',
            table='x',
        ),
    ]
