# Generated by Django 4.2.6 on 2023-10-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bollapp', '0003_alter_fieldmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservemodel',
            table=None,
        ),
    ]
