# Generated by Django 4.2.6 on 2023-10-16 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bollapp', '0006_alter_reservemodel_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservemodel',
            name='day',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
